import assert from 'node:assert/strict'
import { mkdir } from 'node:fs/promises'

// Run against tests/ui/vite.config.mjs. Supply Playwright and a browser already installed locally.
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright')
const browser = await chromium.launch({ headless: true, executablePath: process.env.CHROME_PATH })
const base = process.env.PRACTICE_UI_URL || 'http://127.0.0.1:5188/tests/ui/practice.html'
const output = process.env.PRACTICE_UI_OUTPUT || '/tmp/tokensmith-practice-ui'
await mkdir(output, { recursive: true })
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } })
page.setDefaultTimeout(10000)
const errors = []
page.on('pageerror', error => errors.push(error.message))
const practice = page.locator('.practice-frame')
const open = async suffix => {
  await page.goto(`${base}?run=${crypto.randomUUID()}${suffix}`)
  await page.getByRole('button', { name: 'Practice', exact: true }).filter({ visible: true }).click()
  await practice.getByRole('button', { name: 'Start practice' }).waitFor()
}
const start = async () => {
  await practice.getByRole('button', { name: 'Start practice' }).click()
  await practice.getByLabel('Your answer', { exact: true }).waitFor()
  await practice.locator('.practice-pending').waitFor({ state: 'hidden' })
}
const grade = async (revision = false) => {
  const count = await page.evaluate(() => window.practiceTest.state().practice.sessions[0].questions[0].attempts.length)
  await practice.getByLabel(revision ? 'Revise your answer' : 'Your answer', { exact: true }).fill(revision ? 'The path is needed to backtrack to update a parent after a split.' : 'The path is needed to backtrack.')
  await practice.getByRole('button', { name: revision ? 'Check revision' : 'Check answer', exact: true }).click()
  await page.waitForFunction(count => window.practiceTest.state().practice.sessions[0].questions[0].attempts.length > count, count)
}
const kinds = () => page.evaluate(() => window.practiceTest.calls.map(call => call.kind))
try {
  await page.goto(`${base}?run=${crypto.randomUUID()}&error-next`)
  const composer = page.locator('.composer textarea')
  await composer.fill('Keep my chat draft.')
  await page.getByRole('button', { name: 'Practice', exact: true }).filter({ visible: true }).click()
  await practice.getByLabel('Buffer pool.txt', { exact: true }).uncheck()
  assert.equal(await practice.getByLabel('Database Systems', { exact: true }).evaluate(el => el.indeterminate), true)
  await practice.getByLabel('Poems', { exact: true }).check()
  await practice.getByLabel('Poems', { exact: true }).uncheck()
  await page.screenshot({ path: `${output}/scope-desktop.png` })
  await start()
  assert.deepEqual(await page.evaluate(() => window.practiceTest.calls.find(c => c.kind === 'sources').selected.map(d => d.documentId)), [1])
  assert.equal(await page.evaluate(() => window.practiceTest.state().materials.find(m => m.id === 'c2').isActive), false)
  await practice.getByRole('button', { name: 'Chat', exact: true }).click()
  assert.equal(await composer.inputValue(), 'Keep my chat draft.')
  await page.getByRole('button', { name: 'Practice', exact: true }).filter({ visible: true }).click()
  await grade()
  assert.equal(await practice.getByRole('region', { name: 'Your submitted answer' }).isVisible(), true)
  assert.equal(await practice.getByRole('region', { name: 'Worked explanation' }).count(), 0)
  assert.match(await practice.getByRole('button', { name: 'Revise answer', exact: true }).getAttribute('class'), /is-primary/)
  assert.equal(await practice.getByText('What to explain', { exact: true }).isVisible(), true)
  assert.equal((await kinds()).filter(k => k === 'question').length, 1)
  await practice.getByText('Supporting passages (1)', { exact: true }).click()
  await practice.locator('.practice-source').click()
  await page.getByRole('dialog', { name: 'Source Markdown viewer' }).waitFor()
  await page.getByRole('button', { name: 'Close Markdown viewer' }).click()
  await page.screenshot({ path: `${output}/feedback-desktop.png` })
  await practice.getByRole('button', { name: 'Next question', exact: true }).click()
  await practice.getByRole('alert').waitFor()
  assert.equal(await practice.getByRole('region', { name: 'Practice feedback' }).isVisible(), true)
  assert.equal(await page.evaluate(() => window.practiceTest.state().practice.sessions[0].questions.length), 1)
  await practice.getByRole('button', { name: 'Revise answer', exact: true }).click()
  assert.equal(await practice.getByLabel('Revise your answer', { exact: true }).inputValue(), 'The path is needed to backtrack.')
  assert.equal(await practice.getByRole('region', { name: 'Practice feedback' }).isVisible(), true)
  await practice.getByLabel('Revise your answer', { exact: true }).fill('Discard this change.')
  await practice.getByRole('button', { name: 'Cancel revision', exact: true }).click()
  assert.match(await practice.getByRole('region', { name: 'Your submitted answer' }).innerText(), /The path is needed to backtrack/)
  await practice.getByRole('button', { name: 'Revise answer', exact: true }).click()
  await grade(true)
  assert.equal(await practice.getByText('Since your last answer', { exact: true }).isVisible(), true)
  assert.match(await practice.getByRole('button', { name: 'Next question', exact: true }).getAttribute('class'), /is-primary/)
  await practice.getByRole('button', { name: 'Show explanation', exact: true }).click()
  await practice.getByRole('region', { name: 'Worked explanation' }).waitFor()
  assert.equal(await page.evaluate(() => window.practiceTest.state().practice.sessions[0].questions[0].attempts[1].assisted), true)
  await practice.getByRole('button', { name: 'Discuss this', exact: true }).click()
  assert.equal(await composer.inputValue(), 'Can you help me understand this?')
  assert.match(await page.locator('.composer').innerText(), /Correct/)
  await page.getByRole('button', { name: 'Send message', exact: true }).click()
  await page.waitForFunction(() => window.practiceTest.calls.some(c => c.kind === 'discussion'))
  const discussion = await page.evaluate(() => window.practiceTest.calls.find(c => c.kind === 'discussion').request)
  assert.match(discussion.selectedPassage.question, /Why does insertion/)
  assert.match(discussion.selectedPassage.question, /My answer: The path/)
  assert.equal(discussion.retrievedSources[0].documentId, 1)
  await page.getByRole('button', { name: 'Practice', exact: true }).filter({ visible: true }).click()
  assert.equal(await practice.getByRole('region', { name: 'Practice feedback' }).isVisible(), true)
  await page.reload()
  await practice.getByRole('region', { name: 'Practice feedback' }).waitFor()
  assert.equal(await page.evaluate(() => window.practiceTest.state().practice.sessions[0].questions[0].attempts.length), 2)
  await practice.getByRole('button', { name: 'Finish session', exact: true }).click()
  await practice.getByRole('heading', { name: 'Your practice recap' }).waitFor()
  await page.screenshot({ path: `${output}/recap-desktop.png` })

  await open('')
  await start()
  await practice.getByRole('button', { name: 'Hint', exact: true }).click()
  await practice.getByRole('heading', { name: 'Hint', exact: true }).waitFor()
  await practice.getByRole('button', { name: 'Hint', exact: true }).click()
  assert.equal((await kinds()).filter(k => k === 'hint').length, 0)
  await practice.getByRole('button', { name: 'Show explanation', exact: true }).click()
  await practice.getByRole('region', { name: 'Worked explanation' }).waitFor()
  assert.equal((await kinds()).filter(k => k === 'answer').length, 0)
  assert.deepEqual((await kinds()).filter(k => ['question', 'feedback', 'answer', 'hint'].includes(k)), ['question'])
  await practice.getByRole('button', { name: 'Revise answer', exact: true }).click()
  await grade()
  assert.equal(await page.evaluate(() => window.practiceTest.state().practice.sessions[0].questions[0].attempts[0].assisted), true)
  await practice.getByRole('button', { name: 'Next question', exact: true }).click()
  await page.waitForFunction(() => window.practiceTest.state().practice.sessions[0].questions.length === 2)
  await practice.getByRole('button', { name: 'Previous question', exact: true }).click()
  assert.equal(await practice.getByRole('region', { name: 'Worked explanation' }).isVisible(), true)
  await practice.getByRole('button', { name: 'Next question', exact: true }).click()
  for (let index = 1; index < 5; index++) {
    await practice.getByRole('button', { name: 'Show explanation', exact: true }).click()
    await practice.getByRole('region', { name: 'Worked explanation' }).waitFor()
    await practice.getByRole('button', { name: index === 4 ? 'Finish practice' : 'Next question', exact: true }).click()
    if (index < 4) await page.waitForFunction(count => window.practiceTest.state().practice.sessions[0].questions.length === count, index + 2)
  }
  await practice.getByRole('heading', { name: 'Your practice recap' }).waitFor()
  assert.equal(await page.evaluate(() => window.practiceTest.state().practice.sessions[0].questions.length), 5)
  assert.equal(await practice.getByText('Revisit this concept', { exact: true }).isVisible(), true)

  await open('&error-feedback')
  await start()
  await practice.getByLabel('Your answer', { exact: true }).fill('My answer is preserved.')
  await practice.getByRole('button', { name: 'Check answer', exact: true }).click()
  await practice.getByRole('alert').waitFor()
  assert.equal(await practice.getByLabel('Your answer', { exact: true }).inputValue(), 'My answer is preserved.')
  assert.equal(await page.evaluate(() => window.practiceTest.state().practice.sessions[0].questions[0].attempts.length), 0)
  await grade()

  await open('&question-issue')
  await start()
  await grade()
  assert.equal(await practice.getByText('Question needs review', { exact: true }).isVisible(), true)
  assert.equal(await practice.getByText('What to explain', { exact: true }).count(), 0)
  assert.match(await practice.getByRole('button', { name: 'Next question', exact: true }).getAttribute('class'), /is-primary/)

  await open('&slow-sources')
  await practice.getByRole('button', { name: 'Start practice' }).click()
  await practice.getByRole('button', { name: 'Stop', exact: true }).click()
  await page.waitForTimeout(2300)
  assert.equal((await kinds()).filter(k => k === 'question').length, 0)
  await practice.getByRole('button', { name: 'Prepare first question' }).waitFor()

  await open('&slow-model')
  await practice.getByRole('button', { name: 'Start practice' }).click()
  await page.waitForFunction(() => window.practiceTest.calls.some(c => c.kind === 'question'))
  await practice.getByRole('complementary', { name: 'Practice sessions' }).getByRole('button', { name: 'New practice', exact: true }).click()
  await page.waitForTimeout(2300)
  assert.equal(await page.evaluate(() => window.practiceTest.state().practice.sessions[0].questions.length), 0)
  assert.equal(await practice.getByRole('heading', { name: 'What would you like to practice?' }).isVisible(), true)

  await page.setViewportSize({ width: 390, height: 844 })
  await open('')
  await page.screenshot({ path: `${output}/scope-mobile.png` })
  await start()
  await grade()
  await page.screenshot({ path: `${output}/feedback-mobile.png` })
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true)
  assert.deepEqual(errors, [])
  console.log('Practice UI passed: scope, draft preservation, feedback, retry, failed next, discussion, reload, recap, cached help, cancellation, stale results, desktop and mobile.')
  console.log(`Screenshots: ${output}`)
} catch (error) {
  await page.screenshot({ path: `${output}/failure.png` })
  console.error(await page.locator('body').innerText())
  throw error
} finally {
  await browser.close()
}
